// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQSk6FQfAE13KpgN6-7t-CPLc2X0JBzQQ',
    appId: '1:436974429429:web:365bdc9ebcddc04bd891bc',
    messagingSenderId: '436974429429',
    projectId: 'moodiary-b37ca',
    authDomain: 'moodiary-b37ca.firebaseapp.com',
    storageBucket: 'moodiary-b37ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQXrb1eCof7ykVbGosP4VeLU1l_n2QZA',
    appId: '1:436974429429:android:de717ff64c908c2ed891bc',
    messagingSenderId: '436974429429',
    projectId: 'moodiary-b37ca',
    storageBucket: 'moodiary-b37ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTCd7cB-qU6E4NRqObhXnzub2YcdCSDU0',
    appId: '1:436974429429:ios:e2dff83fc9ea0671d891bc',
    messagingSenderId: '436974429429',
    projectId: 'moodiary-b37ca',
    storageBucket: 'moodiary-b37ca.appspot.com',
    androidClientId: '436974429429-uo7ib4u99p3fmv6jkdnm757rlcrk8qn2.apps.googleusercontent.com',
    iosClientId: '436974429429-67rminqsrbvnphgd8k9e5jfq7ba3if9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodiary',
  );

}